API_HOST_URL: 'http://10.0.2.2:8000' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
PLATFORM_NAME: 'Your platform name here'
PLATFORM_DESTINATION_NAME: 'example.com'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'

#NEW_LOGISTRATION_ENABLED: false
#COURSE_SHARING_ENABLED: true
#DISCUSSIONS_ENABLED: true
#CERTIFICATES_ENABLED: true
#USER_PROFILES_ENABLED: true
#COURSE_VIDEOS_ENABLED: true
#COURSE_DATES_ENABLED: true
#USING_VIDEO_PIPELINE: false
#ANNOUNCEMENTS_ENABLED: true
#TAB_LAYOUTS_ENABLED: true

#DISCOVERY :
#  COURSE:
#    TYPE : 'webview'
#    BASE_URL: 'https://bangabandhu.online/courses'
#    SEARCH_ENABLED: true
#    SUBJECT_FILTER_ENABLED: true

#YOUTUBE_PLAYER:
#  Enabled: true
#  API_KEY: ''
